require("utility/style-data")
require("prototypes/facility")
require("prototypes/coin")
require("prototypes/gui-styles")
require("prototypes/gui-icons")
require("prototypes/software")
require("prototypes/blocked-recipes")
